version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homedashboard
    ports:
      - "5432:5432"
  backend:
    build: ../backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
